// src/lib/components/ui/Chip.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';

	interface Props extends HTMLButtonAttributes {
		active?: boolean;
	}

	let { active = false, class: className = '', children, ...rest }: Props = $props();
</script>

<button
	type="button"
	aria-pressed={active}
	class={[
		'rounded-full px-3 py-1 text-sm capitalize transition',
		active ? 'bg-clay text-white shadow-sm' : 'bg-stone-100 text-stone-600 hover:bg-stone-200',
		className
	]}
	{...rest}
>
	{@render children?.()}
</button>

// frontend/src/components/Chip.tsx
import type { ButtonHTMLAttributes } from 'react';

interface ChipProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  active?: boolean;
}

export default function Chip({ active = false, className = '', ...props }: ChipProps) {
  return (
    <button
      type="button"
      aria-pressed={active}
      className={`rounded-full px-3 py-1 text-sm capitalize transition ${
        active ? 'bg-clay text-white shadow-sm' : 'bg-stone-100 text-stone-600 hover:bg-stone-200'
      } ${className}`}
      {...props}
    />
  );
}
