// src/lib/components/recipe-list/SearchBar.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { Search } from '@lucide/svelte';
	import { m } from '#lib/paraglide/messages.js';

	interface Props {
		value: string;
		oninput?: () => void;
	}

	let { value = $bindable(), oninput }: Props = $props();

	// What the server rendered. With a defaultValue, hydration leaves the typed value and selection be.
	const initial = untrack(() => value);
</script>

<div class="relative">
	<Search
		class="pointer-events-none absolute top-1/2 left-3.5 h-4 w-4 -translate-y-1/2 text-stone-400"
	/>
	<input
		type="search"
		bind:value
		defaultValue={initial}
		oninput={() => oninput?.()}
		aria-label={m.recipes_list_search_placeholder()}
		placeholder={m.recipes_list_search_placeholder()}
		class="w-full rounded-full border border-stone-300 bg-white py-2 pr-4 pl-10 text-stone-800 transition-colors hover:border-stone-400 focus:border-clay focus:outline-none"
	/>
</div>

// frontend/src/components/SearchBar.tsx
import { Search } from 'lucide-react';
import { useTranslation } from 'react-i18next';

interface SearchBarProps {
  value: string;
  onChange: (value: string) => void;
}

export default function SearchBar({ value, onChange }: SearchBarProps) {
  const { t } = useTranslation();
  return (
    <div className="relative">
      <Search className="pointer-events-none absolute top-1/2 left-3.5 h-4 w-4 -translate-y-1/2 text-stone-400" />
      <input
        type="search"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        aria-label={t('recipes.list.searchPlaceholder')}
        placeholder={t('recipes.list.searchPlaceholder')}
        className="focus:border-clay w-full rounded-full border border-stone-300 bg-white py-2 pr-4 pl-10 text-stone-800 transition-colors hover:border-stone-400 focus:outline-none"
      />
    </div>
  );
}
