// frontend/src/components/TimeStat.tsx
import { Clock, Flame, Timer } from 'lucide-react';
import { useTranslation } from 'react-i18next';

type TimeStatIcon = 'clock' | 'flame' | 'timer';

interface TimeStatProps {
  icon: TimeStatIcon;
  label: string;
  /** `null` renders a dash — the version-history page shows a time one side lacks. */
  minutes: number | null;
}

function StatIcon({ icon }: { icon: TimeStatIcon }) {
  const className = 'h-5 w-5';

  if (icon === 'flame') return <Flame className={className} strokeWidth={1.5} />;
  if (icon === 'timer') return <Timer className={className} strokeWidth={1.5} />;
  return <Clock className={className} strokeWidth={1.5} />;
}

export default function TimeStat({ icon, label, minutes }: TimeStatProps) {
  const { t } = useTranslation();
  return (
    <div className="flex items-center gap-2 text-stone-600">
      <span className="bg-clay/10 text-clay flex h-9 w-9 items-center justify-center rounded-full">
        <StatIcon icon={icon} />
      </span>
      <div className="leading-tight">
        <div className="text-xs text-stone-400">{label}</div>
        <div className="text-sm font-medium text-stone-700">
          {minutes === null ? '—' : t('common.minutes', { count: minutes })}
        </div>
      </div>
    </div>
  );
}

// src/lib/components/recipe/TimeStat.svelte
<script lang="ts">
	import { Clock, Flame, Timer } from '@lucide/svelte';
	import { m } from '#lib/paraglide/messages.js';

	type TimeStatIcon = 'clock' | 'flame' | 'timer';

	interface Props {
		icon: TimeStatIcon;
		label: string;
		/** `null` renders a dash — the version-history page shows a time one side lacks. */
		minutes: number | null;
	}

	let { icon, label, minutes }: Props = $props();

	const Icon = $derived(icon === 'flame' ? Flame : icon === 'timer' ? Timer : Clock);
</script>

<div class="flex items-center gap-2 text-stone-600">
	<span class="flex h-9 w-9 items-center justify-center rounded-full bg-clay/10 text-clay">
		<Icon class="h-5 w-5" strokeWidth={1.5} />
	</span>
	<div class="leading-tight">
		<div class="text-xs text-stone-400">{label}</div>
		<div class="text-sm font-medium text-stone-700">
			{minutes === null ? '—' : m.common_minutes({ count: minutes })}
		</div>
	</div>
</div>
