// frontend/src/components/FilterChips.tsx
import Chip from './Chip';

interface FilterChipItem {
  id: number;
  name: string;
}

interface FilterChipsProps {
  items: FilterChipItem[] | undefined;
  activeValue: string | null;
  onSelect: (value: string | null) => void;
}

export default function FilterChips({ items, activeValue, onSelect }: FilterChipsProps) {
  if (!items || items.length === 0) return null;

  return (
    <div className="flex flex-wrap gap-2">
      <Chip active={!activeValue} onClick={() => onSelect(null)}>
        All
      </Chip>
      {items.map((item) => (
        <Chip
          key={item.id}
          active={activeValue === item.name}
          onClick={() => onSelect(item.name === activeValue ? null : item.name)}
        >
          {item.name}
        </Chip>
      ))}
    </div>
  );
}

// src/lib/components/FilterChips.svelte
<script lang="ts">
	import { m } from '#lib/paraglide/messages.js';
	import Chip from './Chip.svelte';

	interface Props {
		items: { id: number; name: string }[] | undefined;
		/** The selected item's name, or null for "All". */
		active: string | null;
		onselect: (value: string | null) => void;
	}

	let { items, active, onselect }: Props = $props();
</script>

{#if items && items.length > 0}
	<div class="flex flex-wrap gap-2">
		<Chip active={!active} onclick={() => onselect(null)}>{m.common_all()}</Chip>
		{#each items as item (item.id)}
			<Chip
				active={active === item.name}
				onclick={() => onselect(item.name === active ? null : item.name)}
			>
				{item.name}
			</Chip>
		{/each}
	</div>
{/if}
