// frontend/src/components/ShareRecipeDialog.tsx
import { useRef, useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { disableRecipeShare, enableRecipeShare, getRecipeShareUrl } from '../api/client';
import { queryKeys } from '../api/queryKeys';
import type { Recipe } from '../types';
import ConfirmDialog from './ConfirmDialog';
import Dialog from './Dialog';

interface ShareRecipeDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  recipeId: number;
  shareToken: string | null;
}

export default function ShareRecipeDialog({
  open,
  onOpenChange,
  recipeId,
  shareToken,
}: ShareRecipeDialogProps) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const inputRef = useRef<HTMLInputElement>(null);
  const [copied, setCopied] = useState(false);
  const [confirmStopOpen, setConfirmStopOpen] = useState(false);

  // Written straight into the cached recipe so the dialog flips state without
  // waiting on a refetch; the invalidation then confirms it against the server.
  function setCachedToken(token: string | null) {
    queryClient.setQueryData<Recipe>(queryKeys.recipe(recipeId), (recipe) =>
      recipe ? { ...recipe, share_token: token } : recipe
    );
    queryClient.invalidateQueries({ queryKey: queryKeys.recipe(recipeId) });
  }

  const enableMutation = useMutation({
    mutationFn: () => enableRecipeShare(recipeId),
    onSuccess: ({ share_token }) => setCachedToken(share_token),
  });

  const disableMutation = useMutation({
    mutationFn: () => disableRecipeShare(recipeId),
    onSuccess: () => {
      setCachedToken(null);
      setConfirmStopOpen(false);
    },
    // ConfirmDialog has nowhere to show an error, so hand back to the share
    // dialog, which renders it above the still-active link.
    onError: () => {
      setConfirmStopOpen(false);
      onOpenChange(true);
    },
  });

  const shareUrl = shareToken ? getRecipeShareUrl(shareToken) : '';

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // The Clipboard API only exists in secure contexts, and a self-hosted
      // instance may well be served over plain http — leave the link selected
      // so it can be copied by hand.
      inputRef.current?.select();
    }
  }

  function handleStopClick() {
    // One dialog at a time: the confirmation replaces this one rather than
    // stacking on top of it.
    onOpenChange(false);
    setConfirmStopOpen(true);
  }

  const error = enableMutation.error ?? disableMutation.error;

  return (
    <>
      <Dialog
        open={open}
        onOpenChange={onOpenChange}
        title={t('recipes.share.title')}
        description={t('recipes.share.description')}
      >
        {error && <p className="mb-3 text-sm text-red-600">{error.message}</p>}

        {shareToken ? (
          <>
            <label className="mb-1.5 block text-sm font-medium text-stone-700" htmlFor="share-link">
              {t('recipes.share.linkLabel')}
            </label>
            <div className="flex gap-2">
              <input
                ref={inputRef}
                id="share-link"
                type="text"
                readOnly
                value={shareUrl}
                onFocus={(e) => e.currentTarget.select()}
                className="focus:border-clay w-full rounded-md border border-stone-300 bg-stone-50 px-3 py-2 text-[13px] text-stone-600 focus:outline-none"
              />
              <button
                type="button"
                onClick={handleCopy}
                className="bg-clay shrink-0 rounded-md px-4 py-2 text-[13px] text-white"
              >
                {copied ? t('recipes.share.copied') : t('recipes.share.copyLink')}
              </button>
            </div>
            <p className="mt-2 text-xs text-stone-500">{t('recipes.share.hint')}</p>

            <div className="mt-6 flex items-center justify-between gap-2">
              <button
                type="button"
                onClick={handleStopClick}
                className="text-sm text-red-600 hover:underline"
              >
                {t('recipes.share.stop')}
              </button>
              <button
                type="button"
                onClick={() => onOpenChange(false)}
                className="rounded-md border border-stone-300 px-4 py-2 text-sm transition-colors hover:border-stone-400 hover:bg-stone-100"
              >
                {t('recipes.share.done')}
              </button>
            </div>
          </>
        ) : (
          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={() => onOpenChange(false)}
              className="rounded-md border border-stone-300 px-4 py-2 text-sm transition-colors hover:border-stone-400 hover:bg-stone-100"
            >
              {t('common.cancel')}
            </button>
            <button
              type="button"
              onClick={() => enableMutation.mutate()}
              disabled={enableMutation.isPending}
              className="bg-clay hover:bg-clay/90 rounded-md px-4 py-2 text-sm text-white disabled:opacity-50"
            >
              {enableMutation.isPending ? t('common.working') : t('recipes.share.createLink')}
            </button>
          </div>
        )}
      </Dialog>

      <ConfirmDialog
        open={confirmStopOpen}
        onOpenChange={setConfirmStopOpen}
        title={t('recipes.share.stopDialogTitle')}
        description={t('recipes.share.stopDialogDescription')}
        confirmLabel={t('recipes.share.stop')}
        isDanger
        isPending={disableMutation.isPending}
        onConfirm={() => disableMutation.mutate()}
      />
    </>
  );
}

// src/lib/components/ShareRecipeDialog.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { m } from '#lib/paraglide/messages.js';
	import ConfirmDialog from './ConfirmDialog.svelte';
	import Dialog from './Dialog.svelte';

	interface Props {
		open: boolean;
		shareUrl: string | null;
	}

	let { open = $bindable(), shareUrl }: Props = $props();

	let creating = $state(false);
	let copied = $state(false);
	let confirmStopOpen = $state(false);
	let input = $state<HTMLInputElement>();

	async function copy() {
		if (!shareUrl) return;
		try {
			await navigator.clipboard.writeText(shareUrl);
			copied = true;
			setTimeout(() => (copied = false), 2000);
		} catch {
			// The Clipboard API only exists in secure contexts, and a self-hosted instance may be
			// served over plain http: leave the link selected so it can be copied by hand.
			input?.select();
		}
	}

	function stopSharing() {
		// One dialog at a time: the confirmation replaces this one rather than stacking on it.
		open = false;
		confirmStopOpen = true;
	}
</script>

<Dialog bind:open title={m.recipes_share_title()} description={m.recipes_share_description()}>
	{#if shareUrl}
		<label class="mb-1.5 block text-sm font-medium text-stone-700" for="share-link">
			{m.recipes_share_link_label()}
		</label>
		<div class="flex gap-2">
			<input
				bind:this={input}
				id="share-link"
				type="text"
				readonly
				value={shareUrl}
				onfocus={(e) => e.currentTarget.select()}
				class="w-full rounded-md border border-stone-300 bg-stone-50 px-3 py-2 text-[13px] text-stone-600 focus:border-clay focus:outline-none"
			/>
			<button
				type="button"
				onclick={copy}
				class="shrink-0 rounded-md bg-clay px-4 py-2 text-[13px] text-white hover:bg-clay/90"
			>
				{copied ? m.recipes_share_copied() : m.recipes_share_copy_link()}
			</button>
		</div>
		<p class="mt-2 text-xs text-stone-500">{m.recipes_share_hint()}</p>

		<div class="mt-6 flex items-center justify-between gap-2">
			<button type="button" onclick={stopSharing} class="text-sm text-red-600 hover:underline">
				{m.recipes_share_stop()}
			</button>
			<button
				type="button"
				onclick={() => (open = false)}
				class="rounded-md border border-stone-300 px-4 py-2 text-sm transition-colors hover:border-stone-400 hover:bg-stone-100"
			>
				{m.recipes_share_done()}
			</button>
		</div>
	{:else}
		<!-- The page load re-runs after the action and supplies shareUrl; the dialog stays open
		     because its open state lives in the parent. -->
		<form
			method="POST"
			action="?/share"
			use:enhance={() => {
				creating = true;
				return async ({ update }) => {
					await update();
					creating = false;
				};
			}}
			class="flex justify-end gap-2"
		>
			<button
				type="button"
				onclick={() => (open = false)}
				class="rounded-md border border-stone-300 px-4 py-2 text-sm transition-colors hover:border-stone-400 hover:bg-stone-100"
			>
				{m.common_cancel()}
			</button>
			<button
				type="submit"
				disabled={creating}
				class="rounded-md bg-clay px-4 py-2 text-sm text-white hover:bg-clay/90 disabled:opacity-50"
			>
				{creating ? m.common_working() : m.recipes_share_create_link()}
			</button>
		</form>
	{/if}
</Dialog>

<ConfirmDialog
	bind:open={confirmStopOpen}
	title={m.recipes_share_stop_dialog_title()}
	description={m.recipes_share_stop_dialog_description()}
	confirmLabel={m.recipes_share_stop()}
	action="?/unshare"
	danger
/>
