// frontend/src/components/AiErrorBanner.tsx
import { useTranslation } from 'react-i18next';
import { ApiError } from '../api/client';
import { formatRetryAt } from 'yumbry-shared';

interface AiErrorBannerProps {
  error: Error;
}

export default function AiErrorBanner({ error }: AiErrorBannerProps) {
  const { t, i18n } = useTranslation();

  // The server's quota message is English-only and can't name the reader's local time, so a spent
  // budget is the one AI error rendered from the locale files instead.
  let message = error.message;
  if (error instanceof ApiError && error.kind === 'quota_exceeded') {
    const key = error.scope === 'user' ? 'aiQuota.userExceeded' : 'aiQuota.sharedExceeded';
    message = error.retryAt
      ? t(`${key}At`, { time: formatRetryAt(error.retryAt, i18n.language) })
      : t(key);
  }

  return (
    <p
      role="alert"
      className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-600"
    >
      {message}
    </p>
  );
}

// src/lib/components/ai/AiErrorBanner.svelte
<script lang="ts">
	import { m } from '#lib/paraglide/messages.js';
	import { getLocale } from '#lib/paraglide/runtime.js';
	import type { AiQuotaScope } from '#lib/shared/ai/budget.ts';
	import { formatRetryAt } from '#lib/shared/ai/budget-display.ts';

	interface Props {
		message: string;
		kind?: string;
		scope?: AiQuotaScope;
		retryAt?: string | null;
	}

	let { message, kind, scope, retryAt }: Props = $props();

	// The server's quota message is English-only and can't name the reader's local time, so a spent
	// budget is worded here instead.
	const text = $derived.by(() => {
		if (kind !== 'quota_exceeded') return message;
		const user = scope === 'user';
		if (retryAt) {
			const time = formatRetryAt(retryAt, getLocale());
			return user ? m.ai_quota_user_exceeded_at({ time }) : m.ai_quota_shared_exceeded_at({ time });
		}
		return user ? m.ai_quota_user_exceeded() : m.ai_quota_shared_exceeded();
	});
</script>

<p role="alert" class="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-600">
	{text}
</p>
